#!/usr/bin/with-contenv bash
# shellcheck shell=bash

export NODE_ENV=production

# See https://github.com/plankanban/planka/issues/253
export TZ=UTC

if [[ -z ${LSIO_NON_ROOT_USER} ]]; then
    HOME=/config exec \
        s6-notifyoncheck -d -n 300 -w 1000 -c "nc -z localhost 1337" \
        cd /app s6-setuidgid abc node app.js --prod
else
    HOME=/config exec \
        s6-notifyoncheck -d -n 300 -w 1000 -c "nc -z localhost 1337" \
        cd /app node app.js --prod
fi
